"""Add total_cost to Task

Revision ID: 09ae73aad6bf
Revises: 50ffcdc38a4e
Create Date: 2026-03-09 17:35:52.939486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09ae73aad6bf'
down_revision: Union[str, Sequence[str], None] = '50ffcdc38a4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
