"""Add project_content_anchors_2

Revision ID: 2a97225f2970
Revises: 66e7b7bc01f0
Create Date: 2026-03-10 12:23:07.919866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a97225f2970'
down_revision: Union[str, Sequence[str], None] = '66e7b7bc01f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_pca_project_id'), table_name='project_content_anchors')
    op.create_index(op.f('ix_project_content_anchors_id'), 'project_content_anchors', ['id'], unique=False)
    op.create_index(op.f('ix_project_content_anchors_project_id'), 'project_content_anchors', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_content_anchors_project_id'), table_name='project_content_anchors')
    op.drop_index(op.f('ix_project_content_anchors_id'), table_name='project_content_anchors')
    op.create_index(op.f('idx_pca_project_id'), 'project_content_anchors', ['project_id'], unique=False)
    # ### end Alembic commands ###
