"""add exclude_words to authors

Revision ID: 405ed8482003
Revises: bc88319cbdae
Create Date: 2026-03-11 18:36:34.020577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '405ed8482003'
down_revision: Union[str, Sequence[str], None] = 'bc88319cbdae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('exclude_words', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authors', 'exclude_words')
    # ### end Alembic commands ###
