"""Add indexes to Tasks and Prompts

Revision ID: 50ffcdc38a4e
Revises: 
Create Date: 2026-03-09 12:51:51.671191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50ffcdc38a4e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('authors', 'author',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='сюда надо добавлять имена и фамили авторов',
               existing_nullable=True)
    op.alter_column('authors', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('Authors_author_key'), 'authors', type_='unique')
    op.drop_column('authors', 'exclude_words')
    op.alter_column('blueprint_pages', 'keyword_template',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Шаблон ключевого слова. {seed} заменяется на seed_keyword проекта',
               existing_nullable=False)
    op.alter_column('blueprint_pages', 'use_serp',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='false = страница генерируется без SERP/скрапинга (about, privacy, terms)',
               existing_nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_constraint(op.f('blueprint_pages_blueprint_id_page_slug_key'), 'blueprint_pages', type_='unique')
    op.drop_index(op.f('idx_blueprint_pages_blueprint_id'), table_name='blueprint_pages')
    op.drop_index(op.f('idx_blueprint_pages_sort_order'), table_name='blueprint_pages')
    op.drop_table_comment(
        'blueprint_pages',
        existing_comment='Страницы в блупринте. Каждая строка = одна страница сайта',
        schema=None
    )
    op.alter_column('generated_articles', 'title',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    op.alter_column('generated_articles', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('generated_articles', 'html_content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('generated_articles', 'word_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('generated_articles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_articles_task'), table_name='generated_articles')
    op.drop_constraint(op.f('generated_articles_task_id_fkey'), 'generated_articles', type_='foreignkey')
    op.create_foreign_key(None, 'generated_articles', 'tasks', ['task_id'], ['id'])
    op.drop_table_comment(
        'generated_articles',
        existing_comment='Готовые сгенерированные статьи',
        schema=None
    )
    op.alter_column('prompts', 'skip_in_pipeline',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='true = агент пропускается при генерации (результат будет пустой строкой)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('prompts', 'max_tokens',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('4096'))
    op.alter_column('prompts', 'temperature',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=True,
               existing_server_default=sa.text('0.7'))
    op.alter_column('prompts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_prompts_active_agent'), table_name='prompts', postgresql_where='(is_active = true)')
    op.create_index(op.f('ix_prompts_agent_name'), 'prompts', ['agent_name'], unique=False)
    op.create_index(op.f('ix_prompts_is_active'), 'prompts', ['is_active'], unique=False)
    op.drop_table_comment(
        'prompts',
        existing_comment='Промпты для LLM-агентов',
        schema=None
    )
    op.drop_column('prompts', 'created_at')
    op.alter_column('site_blueprints', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_table_comment(
        'site_blueprints',
        existing_comment='Шаблоны типов сайтов: бренд-сайт, слот-сайт и т.д.',
        schema=None
    )
    op.alter_column('site_projects', 'seed_keyword',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Базовое ключевое слово (напр. casinox), подставляется в {seed} keyword_template',
               existing_nullable=False)
    op.alter_column('site_projects', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               comment=None,
               existing_comment='pending | generating | completed | failed',
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('site_projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_site_projects_blueprint_id'), table_name='site_projects')
    op.drop_index(op.f('idx_site_projects_status'), table_name='site_projects')
    op.drop_table_comment(
        'site_projects',
        existing_comment='Конкретный запуск генерации сайта. Автоматически создаёт N задач по блупринту',
        schema=None
    )
    op.alter_column('site_templates', 'pages_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('site_templates', 'usage_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('site_templates', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('idx_templates_site'), table_name='site_templates')
    op.drop_constraint(op.f('site_templates_site_id_fkey'), 'site_templates', type_='foreignkey')
    op.create_foreign_key(None, 'site_templates', 'sites', ['site_id'], ['id'])
    op.drop_table_comment(
        'site_templates',
        existing_comment='HTML-шаблоны страниц для каждого сайта',
        schema=None
    )
    op.drop_column('site_templates', 'updated_at')
    op.drop_column('site_templates', 'created_at')
    op.alter_column('sites', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_table_comment(
        'sites',
        existing_comment='Реестр сайтов (10 сайтов), для которых генерируется контент',
        schema=None
    )
    op.drop_column('sites', 'updated_at')
    op.drop_column('sites', 'created_at')
    op.alter_column('tasks', 'page_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Тип страницы: homepage, category, article, info, legal',
               existing_nullable=False,
               existing_server_default=sa.text("'article'::character varying"))
    op.alter_column('tasks', 'priority',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('tasks', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('tasks', 'step_results',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Результаты каждого шага pipeline (agent_name → {status, result, timestamp})',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('tasks', 'logs',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Массив логов [{ts, level, msg, step}]',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tasks', 'project_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='NULL = обычная задача. Заполнено = задача принадлежит проекту сайта',
               existing_nullable=True)
    op.alter_column('tasks', 'blueprint_page_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Какой странице блупринта соответствует эта задача',
               existing_nullable=True)
    op.drop_index(op.f('idx_tasks_created'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_page_type'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_project_id'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_site'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_status'), table_name='tasks')
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_target_site_id'), 'tasks', ['target_site_id'], unique=False)
    op.drop_constraint(op.f('tasks_target_site_id_fkey'), 'tasks', type_='foreignkey')
    op.drop_constraint(op.f('tasks_author_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'sites', ['target_site_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'authors', ['author_id'], ['id'])
    op.drop_table_comment(
        'tasks',
        existing_comment='Задания на генерацию контента',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'tasks',
        'Задания на генерацию контента',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_author_id_fkey'), 'tasks', 'authors', ['author_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('tasks_target_site_id_fkey'), 'tasks', 'sites', ['target_site_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_tasks_target_site_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.create_index(op.f('idx_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('idx_tasks_site'), 'tasks', ['target_site_id'], unique=False)
    op.create_index(op.f('idx_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_index(op.f('idx_tasks_page_type'), 'tasks', ['page_type'], unique=False)
    op.create_index(op.f('idx_tasks_created'), 'tasks', [sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('tasks', 'blueprint_page_id',
               existing_type=sa.UUID(),
               comment='Какой странице блупринта соответствует эта задача',
               existing_nullable=True)
    op.alter_column('tasks', 'project_id',
               existing_type=sa.UUID(),
               comment='NULL = обычная задача. Заполнено = задача принадлежит проекту сайта',
               existing_nullable=True)
    op.alter_column('tasks', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tasks', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tasks', 'logs',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Массив логов [{ts, level, msg, step}]',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('tasks', 'step_results',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Результаты каждого шага pipeline (agent_name → {status, result, timestamp})',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('tasks', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('tasks', 'priority',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('tasks', 'page_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Тип страницы: homepage, category, article, info, legal',
               existing_nullable=False,
               existing_server_default=sa.text("'article'::character varying"))
    op.add_column('sites', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('sites', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.create_table_comment(
        'sites',
        'Реестр сайтов (10 сайтов), для которых генерируется контент',
        existing_comment=None,
        schema=None
    )
    op.alter_column('sites', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.add_column('site_templates', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('site_templates', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.create_table_comment(
        'site_templates',
        'HTML-шаблоны страниц для каждого сайта',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'site_templates', type_='foreignkey')
    op.create_foreign_key(op.f('site_templates_site_id_fkey'), 'site_templates', 'sites', ['site_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_templates_site'), 'site_templates', ['site_id'], unique=False)
    op.alter_column('site_templates', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('site_templates', 'usage_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('site_templates', 'pages_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_table_comment(
        'site_projects',
        'Конкретный запуск генерации сайта. Автоматически создаёт N задач по блупринту',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_site_projects_status'), 'site_projects', ['status'], unique=False)
    op.create_index(op.f('idx_site_projects_blueprint_id'), 'site_projects', ['blueprint_id'], unique=False)
    op.alter_column('site_projects', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('site_projects', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               comment='pending | generating | completed | failed',
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('site_projects', 'seed_keyword',
               existing_type=sa.VARCHAR(length=500),
               comment='Базовое ключевое слово (напр. casinox), подставляется в {seed} keyword_template',
               existing_nullable=False)
    op.create_table_comment(
        'site_blueprints',
        'Шаблоны типов сайтов: бренд-сайт, слот-сайт и т.д.',
        existing_comment=None,
        schema=None
    )
    op.alter_column('site_blueprints', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('prompts', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.create_table_comment(
        'prompts',
        'Промпты для LLM-агентов',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_prompts_is_active'), table_name='prompts')
    op.drop_index(op.f('ix_prompts_agent_name'), table_name='prompts')
    op.create_index(op.f('idx_prompts_active_agent'), 'prompts', ['agent_name'], unique=True, postgresql_where='(is_active = true)')
    op.alter_column('prompts', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('prompts', 'temperature',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=False,
               existing_server_default=sa.text('0.7'))
    op.alter_column('prompts', 'max_tokens',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('4096'))
    op.alter_column('prompts', 'skip_in_pipeline',
               existing_type=sa.BOOLEAN(),
               comment='true = агент пропускается при генерации (результат будет пустой строкой)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.create_table_comment(
        'generated_articles',
        'Готовые сгенерированные статьи',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'generated_articles', type_='foreignkey')
    op.create_foreign_key(op.f('generated_articles_task_id_fkey'), 'generated_articles', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_articles_task'), 'generated_articles', ['task_id'], unique=False)
    op.alter_column('generated_articles', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('generated_articles', 'word_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('generated_articles', 'html_content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('generated_articles', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('generated_articles', 'title',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    op.create_table_comment(
        'blueprint_pages',
        'Страницы в блупринте. Каждая строка = одна страница сайта',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_blueprint_pages_sort_order'), 'blueprint_pages', ['blueprint_id', 'sort_order'], unique=False)
    op.create_index(op.f('idx_blueprint_pages_blueprint_id'), 'blueprint_pages', ['blueprint_id'], unique=False)
    op.create_unique_constraint(op.f('blueprint_pages_blueprint_id_page_slug_key'), 'blueprint_pages', ['blueprint_id', 'page_slug'], postgresql_nulls_not_distinct=False)
    op.alter_column('blueprint_pages', 'use_serp',
               existing_type=sa.BOOLEAN(),
               comment='false = страница генерируется без SERP/скрапинга (about, privacy, terms)',
               existing_nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('blueprint_pages', 'keyword_template',
               existing_type=sa.VARCHAR(length=500),
               comment='Шаблон ключевого слова. {seed} заменяется на seed_keyword проекта',
               existing_nullable=False)
    op.add_column('authors', sa.Column('exclude_words', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('Authors_author_key'), 'authors', ['author'], postgresql_nulls_not_distinct=False)
    op.alter_column('authors', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('authors', 'author',
               existing_type=sa.TEXT(),
               comment='сюда надо добавлять имена и фамили авторов',
               existing_nullable=True)
    # ### end Alembic commands ###
