"""Add brand seed logic to projects and blueprints

Revision ID: 66e7b7bc01f0
Revises: d4fbd61cf552
Create Date: 2026-03-09 20:06:38.996074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66e7b7bc01f0'
down_revision: Union[str, Sequence[str], None] = 'd4fbd61cf552'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blueprint_pages', sa.Column('keyword_template_brand', sa.String(length=500), nullable=True))
    op.add_column('site_projects', sa.Column('seed_is_brand', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_projects', 'seed_is_brand')
    op.drop_column('blueprint_pages', 'keyword_template_brand')
    # ### end Alembic commands ###
