"""add_last_heartbeat_and_stale

Revision ID: a73a75b2050a
Revises: 37ef8f986c2b
Create Date: 2026-03-11 10:08:15.911503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a73a75b2050a'
down_revision: Union[str, Sequence[str], None] = '37ef8f986c2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_articles', sa.Column('fact_check_status', sa.String(length=20), nullable=True))
    op.add_column('generated_articles', sa.Column('fact_check_issues', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('generated_articles', sa.Column('fact_check_score', sa.Float(), nullable=True))
    op.add_column('generated_articles', sa.Column('needs_review', sa.Boolean(), nullable=True))
    op.alter_column('site_projects', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment='pending | generating | completed | failed | stopped',
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.add_column('tasks', sa.Column('last_heartbeat', sa.DateTime(), nullable=True))
    op.execute("ALTER TYPE task_status ADD VALUE IF NOT EXISTS 'stale'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'last_heartbeat')
    op.alter_column('site_projects', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='pending | generating | completed | failed | stopped',
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_column('generated_articles', 'needs_review')
    op.drop_column('generated_articles', 'fact_check_score')
    op.drop_column('generated_articles', 'fact_check_issues')
    op.drop_column('generated_articles', 'fact_check_status')
    # ### end Alembic commands ###
