"""Add real total_cost column to Task

Revision ID: d4fbd61cf552
Revises: 09ae73aad6bf
Create Date: 2026-03-09 18:09:03.322261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4fbd61cf552'
down_revision: Union[str, Sequence[str], None] = '09ae73aad6bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('total_cost', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'total_cost')
    # ### end Alembic commands ###
